### ISSUE TITLE
C2026 String Too Big in VS2015

### ISSUE THREAD

**Issue by sponge** [RudenkoArts/TIC-80#3]
VS2015 Community Update 3 seems to not like the huge string at https://github.com/RudenkoArts/TIC-80/blob/master/src/wrenapi.c#L39 - it errors out once it hits > 16380 single-byte characters.

This can be worked around by not using \n\ to split up strings. You can do something like this instead:

```
static const char *myLong String = "this is line 1\n"
"this is line2\n"
"this is line3\n";
```

Or you can just split it up halfway through:

```
}                                                                   	                            \n"
"class Tic {                                                                                     	\n\
```

First way is probably cleaner in the long-run.

**Comment by RudenkoArts** [comment]
Thank you! :)
