### ISSUE TITLE
Remap function in map doesn't include optional arguments

### ISSUE THREAD

**Issue by sponge** [RudenkoArts/TIC-80#4]
According to https://github.com/nesbox/TIC-80/wiki/map the remap callback is supposed to have a signature of remap(i, x, y) with x, y being optional. However Tic.map only calls `var ret = remap.call(tile_index)`

Looks like Wren lets you pass extra arguments without issue, so it should be a fairly quick fix.

**Comment by RudenkoArts** [comment]
Hm, yes, ive missed that one. Thank you, i wll fix that.
