### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by sponge** [RudenkoArts/TIC-80#7]
Looks like when the main Game class encounters a runtime error in the constructor, there is nothing in the slot, and wrenGetSlotHandle crashes. I've fixed this in my branch but couldn't PR without it re-submitting all the other merge changes, so here's the single commit: https://github.com/sponge/TIC-80/commit/7ba3c5d7597845f52436ae8f0f88e6a959d00739

This fixes the crash allowing you to see the error printed to the console, and fixes a second crash that would occur on the next run because of an invalid game_class handle.

**Comment by RudenkoArts** [comment]
Thank you!
